# Generated by Django 6.0.2 on 2026-03-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_address_user_address_line1_user_address_line2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('donor', 'Donor'), ('ngo', 'NGO'), ('orphanage', 'Orphanage'), ('old_age_home', 'Old Age Home'), ('hospital', 'Government Hospital')], default='donor', max_length=30),
        ),
    ]
