# Generated by Django 6.0.2 on 2026-03-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='official_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_certificate_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DONOR', 'Donor'), ('HOTEL', 'Hotel'), ('CAFE', 'Cafe'), ('RESTAURANT', 'Restaurant'), ('CANTEEN', 'Canteen'), ('CATERING_SERVICE', 'Catering Service'), ('NGO', 'NGO'), ('ORPHANAGE', 'Orphanage'), ('OLD_AGE_HOME', 'Old Age Home'), ('GOVERNMENT_HOSPITAL', 'Government Hospital')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='website_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
