# Generated by Django 6.0.2 on 2026-03-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_official_email_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DONOR', 'Donor'), ('HOTEL', 'Hotel'), ('CAFE', 'Cafe'), ('RESTAURANT', 'Restaurant'), ('CANTEEN', 'Canteen'), ('CATERING_SERVICE', 'Catering Service'), ('NGO', 'NGO'), ('ORPHANAGE', 'Orphanage'), ('OLD_AGE_HOME', 'Old Age Home'), ('GOVERNMENT_HOSPITAL', 'Government Hospital')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
    ]
