# Generated by Django 6.0.2 on 2026-03-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_role_alter_user_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DONOR', 'Donor'), ('NGO', 'NGO'), ('ORPHANAGE', 'Orphanage'), ('OLD_AGE_HOME', 'Old Age Home'), ('GOVERNMENT_HOSPITAL', 'Government Hospital')], db_index=True, max_length=30),
        ),
    ]
