# Generated by Django 6.0.2 on 2026-04-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_aadhar_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DONOR', 'Donor'), ('NGO', 'NGO'), ('ORPHANAGE', 'Orphanage'), ('OLD_AGE_HOME', 'Old Age Home'), ('GOVERNMENT_HOSPITAL', 'Government Hospital')], db_index=True, max_length=30),
        ),
    ]
