# Generated by Django 6.0.2 on 2026-03-28 13:34

from django.db import migrations


def update_recipient_statuses(apps, schema_editor):
    FoodRequest = apps.get_model('recipients', 'FoodRequest')
    FoodRequest.objects.filter(status='open').update(status='pending')
    FoodRequest.objects.filter(status='fulfilled').update(status='completed')

class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0002_alter_foodrequest_status'),
    ]

    operations = [
        migrations.RunPython(update_recipient_statuses, migrations.RunPython.noop),
    ]
