# Generated by Django 6.0.2 on 2026-03-05 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_foodlisting_driver_foodlisting_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodlisting',
            old_name='donor',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='foodlisting',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='foodlisting',
            name='recipient',
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='listing_type',
            field=models.CharField(choices=[('donation', 'Donation'), ('request', 'Request')], default='donation', max_length=20),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='matched_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
