# Generated by Django 6.0.2 on 2026-03-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0004_foodpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlisting',
            name='listing_type',
            field=models.CharField(choices=[('donation', 'Donation'), ('request', 'Request')], db_index=True, default='donation', max_length=20),
        ),
        migrations.AlterField(
            model_name='foodlisting',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('completed', 'Completed')], db_index=True, default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='foodpost',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('completed', 'Completed'), ('expired', 'Expired')], db_index=True, default='available', max_length=20),
        ),
    ]
