# Generated by Django 6.0.2 on 2026-03-28 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0005_alter_foodlisting_listing_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpost',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_food_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='foodpost',
            name='quantity',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='foodpost',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('accepted', 'Accepted'), ('received', 'Received'), ('expired', 'Expired')], db_index=True, default='available', max_length=20),
        ),
    ]
