# Generated by Django 6.0.2 on 2026-03-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0006_foodpost_accepted_by_alter_foodpost_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('completed', 'Completed'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20),
        ),
    ]
