# Generated by Django 6.0.2 on 2026-03-28 13:34

from django.db import migrations


def update_donor_statuses(apps, schema_editor):
    FoodPost = apps.get_model('donors', 'FoodPost')
    FoodPost.objects.filter(status='available').update(status='pending')
    FoodPost.objects.filter(status='accepted').update(status='assigned')
    FoodPost.objects.filter(status='received').update(status='completed')

class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0007_alter_foodpost_status'),
    ]

    operations = [
        migrations.RunPython(update_donor_statuses, migrations.RunPython.noop),
    ]
