# Generated by Django 6.0.2 on 2026-03-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0008_update_status_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food_posts/'),
        ),
    ]
