# Generated by Django 6.0.2 on 2026-04-06 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0010_add_lat_lng_to_food_post'),
        ('donors', '0010_foodpost_latitude_foodpost_longitude'),
    ]

    operations = [
    ]
